services:
  api:
    build: .
    container_name: deportivo_api
    ports:
      - "5059:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=192.168.122.9;Port=5432;Database=deportivoucn;Username=postgres;Password=${DB_PASSWORD}
      - Google__ClientId=${GOOGLE_CLIENT_ID}
    restart: unless-stopped
