services:
  db:
    image: postgres:16-alpine
    container_name: deportivo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: DeportivoUCN
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: deportivo_api
    ports:
      - "5059:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    restart: unless-stopped

volumes:
  pgdata:
