// <auto-generated />
using DeportivoUCN.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeportivoUCN.Infrastructure.Migrations
{
    [DbContext(typeof(DeportivoUCNContext))]
    partial class DeportivoUCNContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeportivoUCN.Models.Entities.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SportBranchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SportBranchId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("DeportivoUCN.Models.Entities.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("DeportivoUCN.Models.Entities.SportBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainingDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainingSector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("SportBranches");
                });

            modelBuilder.Entity("DeportivoUCN.Models.Entities.Athlete", b =>
                {
                    b.HasOne("DeportivoUCN.Models.Entities.SportBranch", "SportBranch")
                        .WithMany("Athletes")
                        .HasForeignKey("SportBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SportBranch");
                });

            modelBuilder.Entity("DeportivoUCN.Models.Entities.SportBranch", b =>
                {
                    b.HasOne("DeportivoUCN.Models.Entities.Coach", "Coach")
                        .WithMany("SportBranches")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("DeportivoUCN.Models.Entities.Coach", b =>
                {
                    b.Navigation("SportBranches");
                });

            modelBuilder.Entity("DeportivoUCN.Models.Entities.SportBranch", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
